name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

       #Docker
      - name: Build Docker Image
        run: |
          docker build -t tcmtestaccount/amadeus:${{ github.run_number }} -f ./Amadeus/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push tcmtestaccount/amadeus:${{ github.run_number }}
